version: "3.9"

services:
    php:
        container_name: php
        image: php
        volumes:
         - ./:/app
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:80"
        command: php -S 0.0.0.0:80 -t /app

    apache:
        image: httpd:2.4
        ports:
        - 8000:8000
        volumes:
        - ./src:/usr/local/apache2/htdocs